backend:
  name: github
  repo: remedymorgan2-rgb/rnd-news
  branch: main

media_folder: "images"
public_folder: "/rnd-news/images"

collections:
  - name: "news"
    label: "News"
    folder: "content/news"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Category", name: "category", widget: "select", options: ["Politics", "Crime", "Health", "Business", "Sports"]}
      - {label: "Image", name: "image", widget: "image"}
      - {label: "Short Summary", name: "excerpt", widget: "text"}
      - {label: "Breaking News?", name: "breaking", widget: "boolean", default: false}
      - {label: "Full Story", name: "body", widget: "markdown"}
